-- MySQL Script generated by MySQL Workbench
-- Mon Mar 22 03:57:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `hr_available_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_available_permissions` (
  `id_hr_permissions` INT NOT NULL AUTO_INCREMENT,
  `permissions_name` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`id_hr_permissions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hr_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_profiles` (
  `id_hr_profiles` INT NOT NULL AUTO_INCREMENT,
  `hr_firstname` VARCHAR(255) NOT NULL,
  `hr_lastname` VARCHAR(255) NOT NULL,
  `hr_post` VARCHAR(255) NOT NULL,
  `hr_phone_country` VARCHAR(100) NOT NULL,
  `hr_permissions` VARCHAR(255) NULL DEFAULT NULL,
  `hr_phone` INT NOT NULL,
  `hr_additional_phone` INT NULL DEFAULT NULL,
  `hr_available_permissions_id_hr_permissions` INT NOT NULL,
  PRIMARY KEY (`id_hr_profiles`),
  INDEX `fk_hr_profiles_hr_available_permissions1_idx` (`hr_available_permissions_id_hr_permissions` ASC),
  CONSTRAINT `fk_hr_profiles_hr_available_permissions1`
    FOREIGN KEY (`hr_available_permissions_id_hr_permissions`)
    REFERENCES `hr_available_permissions` (`id_hr_permissions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hr_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hr_users` (
  `hr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hr_mail` VARCHAR(200) NOT NULL,
  `hr_phone` INT NOT NULL,
  `hr_password_hash` CHAR(64) NOT NULL,
  `hr_available_permissions_hr_id` INT NOT NULL,
  `hr_profiles_hr_phone_country` VARCHAR(100) NOT NULL,
  `vacancy_id_vacancy` INT NOT NULL,
  `hr_profiles_id_hr_profiles` INT NOT NULL,
  PRIMARY KEY (`hr_id`, `hr_available_permissions_hr_id`, `hr_profiles_hr_phone_country`, `vacancy_id_vacancy`, `hr_profiles_id_hr_profiles`),
  UNIQUE INDEX `hr_mail_UNIQUE` (`hr_mail` ASC) ,
  UNIQUE INDEX `hr_phone_UNIQUE` (`hr_phone` ASC) ,
  INDEX `fk_hr_users_hr_available_permissions_idx` (`hr_available_permissions_hr_id` ASC) ,
  INDEX `fk_hr_users_hr_profiles1_idx` (`hr_profiles_id_hr_profiles` ASC) ,
  CONSTRAINT `fk_hr_users_hr_available_permissions`
    FOREIGN KEY (`hr_available_permissions_hr_id`)
    REFERENCES `hr_available_permissions` (`id_hr_permissions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hr_users_hr_profiles1`
    FOREIGN KEY (`hr_profiles_id_hr_profiles`)
    REFERENCES `hr_profiles` (`id_hr_profiles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `response` (
  `id_response` INT NOT NULL AUTO_INCREMENT,
  `response` INT NOT NULL,
  `vacancy_visitors` INT NOT NULL,
  `relevant_responses` INT NOT NULL,
  `by_location` INT NOT NULL,
  `consider` INT NOT NULL,
  `phone_interview` INT NOT NULL,
  `assessment` INT NOT NULL,
  `interview` INT NOT NULL,
  `offer` INT NOT NULL,
  `hired` INT NOT NULL,
  `discard_by_employer` INT NOT NULL,
  PRIMARY KEY (`id_response`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vacancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vacancy` (
  `id_vacancy` INT NOT NULL AUTO_INCREMENT,
  `vacancy_description` VARCHAR(245) NOT NULL,
  `vacancy_key_skills` VARCHAR(145) NOT NULL,
  `vacancy_schedule` VARCHAR(145) NOT NULL,
  `vacancy_experience` VARCHAR(145) NOT NULL,
  `vacancy_address` VARCHAR(145) NOT NULL,
  `vacancy_employment` VARCHAR(145) NOT NULL,
  `vacancy_salary` INT NULL,
  `vacancy_name` VARCHAR(45) NOT NULL,
  `vacancy_area` VARCHAR(145) NOT NULL,
  `vacancy_created_at` DATETIME NOT NULL DEFAULT NOW(),
  `vacancy_published_at` DATETIME NOT NULL DEFAULT NOW(),
  `vacancy_specialization` VARCHAR(245) NOT NULL,
  `vacancy_contacts` INT NOT NULL,
  `hr_users_hr_id` INT UNSIGNED NOT NULL,
  `hr_users_hr_available_permissions_hr_id` INT NOT NULL,
  `hr_users_hr_profiles_hr_phone_country` VARCHAR(100) NOT NULL,
  `hr_users_vacancy_id_vacancy` INT NOT NULL,
  `response_id_response` INT NOT NULL,
  PRIMARY KEY (`id_vacancy`),
  INDEX `fk_vacancy_hr_users1_idx` (`hr_users_hr_id` ASC, `hr_users_hr_available_permissions_hr_id` ASC, `hr_users_hr_profiles_hr_phone_country` ASC, `hr_users_vacancy_id_vacancy` ASC) ,
  INDEX `fk_vacancy_response1_idx` (`response_id_response` ASC) ,
  CONSTRAINT `fk_vacancy_hr_users1`
    FOREIGN KEY (`hr_users_hr_id` , `hr_users_hr_available_permissions_hr_id` , `hr_users_hr_profiles_hr_phone_country` , `hr_users_vacancy_id_vacancy`)
    REFERENCES `hr_users` (`hr_id` , `hr_available_permissions_hr_id` , `hr_profiles_hr_phone_country` , `vacancy_id_vacancy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacancy_response1`
    FOREIGN KEY (`response_id_response`)
    REFERENCES `response` (`id_response`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contacts` (
  `id_vacancy` INT NOT NULL AUTO_INCREMENT,
  `contacts_name` VARCHAR(145) NULL,
  `contacts_email` VARCHAR(200) NULL DEFAULT NULL,
  `contacts_phones` INT NULL DEFAULT NULL,
  `hr_profiles_id_hr_profiles` INT NOT NULL,
  PRIMARY KEY (`id_vacancy`),
  INDEX `fk_contacts_hr_profiles1_idx` (`hr_profiles_id_hr_profiles` ASC) ,
  CONSTRAINT `fk_contacts_vacancy1`
    FOREIGN KEY (`id_vacancy`)
    REFERENCES `vacancy` (`id_vacancy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contacts_hr_profiles1`
    FOREIGN KEY (`hr_profiles_id_hr_profiles`)
    REFERENCES `hr_profiles` (`id_hr_profiles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `counters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `counters` (
  `id_vacancy_counters` INT NOT NULL AUTO_INCREMENT,
  `counters_views` INT NULL DEFAULT NULL,
  `counters_responses` INT NULL DEFAULT NULL,
  `counters_unread_responses` INT NULL DEFAULT NULL,
  `counters_resumes_in_progress` INT NULL DEFAULT NULL,
  `counters_invitations` INT NULL DEFAULT NULL,
  `vacancy_id_vacancy` INT NOT NULL,
  `vacancy_counters_id_vacancy_counters` INT NOT NULL,
  PRIMARY KEY (`id_vacancy_counters`),
  INDEX `fk_counters_vacancy1_idx` (`vacancy_id_vacancy` ASC, `vacancy_counters_id_vacancy_counters` ASC) ,
  CONSTRAINT `fk_counters_vacancy1`
    FOREIGN KEY (`vacancy_id_vacancy`)
    REFERENCES `vacancy` (`id_vacancy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skills` (
  `id_skills` INT NOT NULL AUTO_INCREMENT,
  `skills_name` VARCHAR(245) NOT NULL,
  `skills_specializations` VARCHAR(245) NOT NULL,
  `vacancy_id_vacancy` INT NOT NULL,
  `vacancy_counters_id_vacancy_counters` INT NOT NULL,
  PRIMARY KEY (`id_skills`),
  INDEX `fk_skills_vacancy1_idx` (`vacancy_id_vacancy` ASC, `vacancy_counters_id_vacancy_counters` ASC) ,
  CONSTRAINT `fk_skills_vacancy1`
    FOREIGN KEY (`vacancy_id_vacancy`)
    REFERENCES `vacancy` (`id_vacancy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resume_search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resume_search` (
  `id_resume_search` INT NOT NULL AUTO_INCREMENT,
  `resume_search` VARCHAR(45) NULL,
  `prof_field` ENUM("Информационные технологии, интернет, телеком", "Маркетинг", "Продажи", "Строительство, недвижимость", "Медицина, фармацевтика", "Другое") NULL DEFAULT NULL,
  `location` VARCHAR(45) NULL DEFAULT NULL,
  `metro` VARCHAR(45) NULL DEFAULT NULL,
  `salary` FLOAT NULL DEFAULT NULL,
  `education` ENUM("Не имеет значение", "Высшее", "Бакалавр", "Магистр", "Кандидат наук", "Доктор наук", "Незаконченное высшее", "Среднее", "Средне-специальное") NULL DEFAULT NULL,
  `nationality` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `gender` ENUM("Не имеет значения", "Мужской", "Женский") NULL DEFAULT NULL,
  `employment` ENUM("	Полная занятость", "Частичная занятость ", "Проектная работа/разовое задание", "Волонтерство", "Стажировка") NULL DEFAULT NULL,
  `work_schedule` ENUM("	Полный день", "Сменный график", "Гибкий график", "	Удаленная работа", "Вахтовый метод") NULL DEFAULT NULL,
  `car` ENUM("Есть личный автомобиль", "Нет личного автомобиля") NULL DEFAULT NULL,
  `hr_users_hr_id` INT UNSIGNED NOT NULL,
  `hr_users_hr_available_permissions_hr_id` INT NOT NULL,
  `hr_users_hr_profiles_hr_phone_country` VARCHAR(100) NOT NULL,
  `hr_users_vacancy_id_vacancy` INT NOT NULL,
  INDEX `fk_resume_search_hr_users1_idx` (`hr_users_hr_id` ASC, `hr_users_hr_available_permissions_hr_id` ASC, `hr_users_hr_profiles_hr_phone_country` ASC, `hr_users_vacancy_id_vacancy` ASC) ,
  PRIMARY KEY (`id_resume_search`),
  CONSTRAINT `fk_resume_search_hr_users1`
    FOREIGN KEY (`hr_users_hr_id` , `hr_users_hr_available_permissions_hr_id` , `hr_users_hr_profiles_hr_phone_country` , `hr_users_vacancy_id_vacancy`)
    REFERENCES `hr_users` (`hr_id` , `hr_available_permissions_hr_id` , `hr_profiles_hr_phone_country` , `vacancy_id_vacancy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `media` (
  `id_vacancy` INT NOT NULL AUTO_INCREMENT,
  `media_types_id` INT UNSIGNED NOT NULL,
  `hr_id` INT UNSIGNED NOT NULL,
  `size` BIGINT NOT NULL,
  `file` VARCHAR(45) NULL DEFAULT NULL,
  `vacancy_id_vacancy` INT NOT NULL,
  `vacancy_counters_id_vacancy_counters` INT NOT NULL,
  `blob` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_vacancy`),
  INDEX `fk_media_vacancy1_idx` (`vacancy_id_vacancy` ASC, `vacancy_counters_id_vacancy_counters` ASC) ,
  CONSTRAINT `fk_media_vacancy1`
    FOREIGN KEY (`vacancy_id_vacancy`)
    REFERENCES `vacancy` (`id_vacancy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
